version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: WindowsAzure.ServiceBus
    versions:
    - 6.0.3
    - 6.0.4
    - 6.0.5
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
